# Given a bound pdb file, write i-zone file
#
# I-RMSD def: “To that end, the interface residues in the target were redefined as those having at least one atom within 10 Å of an atom on the other molecule. This is twice the threshold used in defining the residue–residue contacts described above. The backbone of these residues were then superimposed on their equivalents in the predicted complex to compute the I_RMS”. [Méndez et al. 2003]
#
# NOTE: The bound pdb file has to have the same atomResNum as in the docked models


# Li Xue
# March 10th, 2015

pdbFL_bound=$1


if [ -z $pdbFL_bound  ];then
    echo
    echo "Usage: i_zone.sh pdbFL_bound"
    echo
    exit
fi



pdb_chainxseg $pdbFL_bound > $pdbFL_bound.tmp

FLname=`basename $pdbFL_bound ".pdb"`
/home/software/haddock/haddock2.2/tools/contact $pdbFL_bound.tmp 10 > $FLname.contacts_10A


echo "# generated by $0 $1" > $FLname.izone

#-- the format of contact file:
#
# 3 A CB 24 B CA 9.964252
# 3 A CB 24 B C 9.951800
# 3 A CB 24 B O 9.037468

#-- izone for the first chain
awk '{print "zone " $2 $1 "-" $2 $1}' $FLname.contacts_10A >> $FLname.izone

#izone for the second chain

awk '{print "zone " $5 $4 "-" $5 $4}' $FLname.contacts_10A >> $FLname.izone


#--
sort -u $FLname.izone > tmp
mv tmp $FLname.izone

#--clean up

rm $pdbFL_bound.tmp
rm $FLname.contacts_10A


#--
echo "$FLname.izone generated"

