# Given a bound pdb file, write i-zone file
#
# I-RMSD def: “To that end, the interface residues in the target were redefined as those having at least one atom within 10 Å of an atom on the other molecule. This is twice the threshold used in defining the residue–residue contacts described above. The backbone of these residues were then superimposed on their equivalents in the predicted complex to compute the I_RMS”. [Méndez et al. 2003]
#
# NOTE: The bound pdb file has to have the same atomResNum as in the docked models
#
# OUTPUT i-zone file format:
# zone A100-A100
# zone A101-A101


# Li Xue
# March 10th, 2015

pdbFL_bound=$1


if [ -z $pdbFL_bound  ];then
    echo
    echo "Usage: i_zone.sh pdbFL_bound"
    echo
    exit
fi



pdb_chainxseg $pdbFL_bound > $pdbFL_bound.tmp

FLname=`basename $pdbFL_bound ".pdb"`
contact-chainID_allAtoms $pdbFL_bound.tmp 10 > $FLname.contacts_10A

exit


# write the header line in izone file
echo "# generated by $0 $1" > $FLname.izone

#-- the format of contact file:
#
# ILE     A          3     N       1581   PHE     B         13     CB      1581   9.05491855
# ILE     A          3     N       1582   PHE     B         13     CG      1582   8.96164165

#-- izone for the first chain
# awk '{print "zone " $2 $1 "-" $2 $1}' $FLname.contacts_10A >> $FLname.izone
awk '{print "zone " $2 $3 "-" $2 $3}' $FLname.contacts_10A >> $FLname.izone

#izone for the second chain

awk '{print "zone " $7 $8 "-" $7 $8}' $FLname.contacts_10A >> $FLname.izone


#--
sort -u $FLname.izone > tmp
mv tmp $FLname.izone

#--clean up

rm $pdbFL_bound.tmp
rm $FLname.contacts_10A


#--
echo "$FLname.izone generated"

