#!/usr/bin/env python
"""

Scan the contact list generated by contact, and keep CA or CB contacts with specified chain ID and residue number.

Usage: extract_contacts.py contact.list P 2 (keep CA and CB contacts from chain P residue 2)

Li Xue
6-Jul-2018 12:33
"""

import sys
import re

USAGE = __doc__.format()

if (len(sys.argv) != 4):
    sys.stderr.write(USAGE)
    sys.exit(1)


contactFL = sys.argv[1]
keep_chn = sys.argv[2]
keep_resi = sys.argv[3]

f = open(contactFL,'r')
contacts = [ l.strip() for l in f if re.search('^\w{3}', l) ]
f.close()

for line in contacts:
#  GLU A     58     CA      2137   ASP D     26     CA      2137   7.92322586
#  GLU A     58     CA      2163   GLY D     28     CA      2163   7.68690607


    aa1, chn1, resinum1, atom1, atomNum1, aa2, chn2, resinum2, atom2, atomNum2, distance = re.split('\s+',line)

    condition1 = (chn1 == keep_chn and resinum1 == keep_resi and re.match('(CA|CB)', atom1) )
    condition2 = (chn2 == keep_chn and resinum2 == keep_resi and re.match('(CA|CB)', atom2) )

    if condition1 or condition2:
        print (line)







